### PR TITLE
Add basic support for passing command-line arguments to commands

### PR DESCRIPTION
**Pull request by nacx**

### CODE REVIEW

**Comment by wagoodman** [comment]
Thanks for taking the time to add this feature (and tests!), it's really needed. 

I have one medium-sized change, instead of a csv list of options it would be more natural to allow users to add positional arguments as they would for a bash script, so instead of `bashful run some.yaml --args 10,20,30` do something like `bashful run some.yaml 10 20 30`. In this way developers would inherently already know what `$1` `$2` and `$3` are.

What are your thoughts?

**Comment by nacx** [comment]
Yes, sounds better. I'll change it that way 😀

**Comment by nacx** [comment]
Done!

**Comment by wagoodman** [comment]
Looks great, thanks again!

**Comment by RyoshiKayo** [comment]
Can this be added to the README? I didn't know that this was a thing till I thought to make a feature request, and was searching through merged PR's.

**Comment by wagoodman** [comment]
@RyoshiKayo  good point! Added in d4ddaa002ec461c70bde93ed01716681248e7514

**Pull request merged**
